parameters:
    oro_installer.scenario.class:                     Oro\Bundle\InstallerBundle\Process\InstallerScenario
    oro_installer.yaml_persister.class:               Oro\Bundle\InstallerBundle\Persister\YamlPersister
    oro_installer.listener.request.class:             Oro\Bundle\InstallerBundle\EventListener\RequestListener
    oro_installer.script_manager.class:               Oro\Bundle\InstallerBundle\ScriptManager
    oro_installer.helper.requirements_helper.class:   Oro\Bundle\InstallerBundle\Helper\RequirementsHelper

    oro_installer.event_listener.requirements_listener.class: Oro\Bundle\InstallerBundle\EventListener\RequirementsListener
services:
    oro_installer.scenario:
        class: %oro_installer.scenario.class%
        calls:
          - [ setContainer, ["@service_container"] ]
        tags:
          - { name: sylius.process.scenario, alias: oro_installer }

    oro_installer.yaml_persister:
        class: %oro_installer.yaml_persister.class%
        arguments:
            - %kernel.root_dir%/config
            - %kernel.environment%

    kernel.listener.install.event:
        class: %oro_installer.listener.request.class%
        arguments:
            - "@router"
            - %installed%
            - %kernel.debug%

    oro_installer.script_manager:
        class: %oro_installer.script_manager.class%
        arguments:
            - @kernel

    oro_installer.helper.requirements_helper:
        class: %oro_installer.helper.requirements_helper.class%
        arguments:
            - %kernel.root_dir%

    oro_installer.event_listener.requirements_listener:
        class: %oro_installer.event_listener.requirements_listener.class%
        arguments:
            - @oro_installer.helper.requirements_helper
        tags:
            - { name: kernel.event_listener, event: console.command }
